logger:
  # This logger will output a txt file in tum style
  enable_pose_logger: false
  pose_log_file: "/home/neofelis/Code/drift/log/mini_cheetah.txt"
  vel_log_file: "/home/justin/code/drift/log/mini_cheetah_vel_log.txt"
  pose_log_rate: 10 # Hz

state:
  rotation_std_value: 0.1
  velocity_std_value: 0.1
  position_std_value: 0.001