# Settings for IMU propagation model
settings:
  ###################
  # Filter Settings #
  ###################
  static_bias_initialization: true  # Enable this the filter will use the first N data points
                                    # to initialize bias with the assumption of robot being static.
                                    # If you set this to false, remember to also change the bias
                                    # prior in config/prior.yaml.
  init_bias_size: 250 # The number of data points used to initialize bias.
  init_bias_using_orientation_est_from_imu: false # Enable this the filter will use the orientation
                                                  # estimated from the imu to initialize bias. 
                                                  # Setting this to false the filter will assume
                                                  # the robot to be horizontally static (gravity pointing
                                                  # downwards) to initialize the filter.   
  enable_imu_bias_update: false # Enable imu bias update or not.
  use_imu_ori_est_init_bias: false # Use the orientation estimated from the imu to initialize bias.

  ########################
  # Orientation Settings #
  ########################
  # We assume the body frame to be at the imu position.
  # X pointing forward, Y to the left, Z pointing up.
  # rotation_imu2body: [0, 0.7071, -0.7071, 0] # Orientation from IMU to the body frame. [w, x, y, z]
  rotation_imu2body: [1, 0, 0, 0] # Orientation from IMU to the body frame. [w, x, y, z]

# IMU bias prior:
priors:
  # gyroscope_bias: [-0.009514, 0.01402, 0.01869] 
  # accelerometer_bias: [0.00286941, -0.0323794, -0.00220881]

  # 2023-02-15-13-29-37 (Carpet 1)
  # gyroscope_bias: [-0.007307372585365693, 0.022668456301323314, -0.008560273614140953]
  # accelerometer_bias: [0.192374, -0.2169, -0.00656462]

  # 2023-02-15-15-02-07 (Corridor right turn)
  # gyroscope_bias: [-0.012044923295857981,  0.023609350251479276, -0.0089126130562130166]
  # accelerometer_bias: [0.221345, -0.25936, -0.0013529]

  # 2023-02-18-09-46-24 (Corridor lab to gate)
  # gyroscope_bias: [-0.007821179613320262,  0.02305523649179605, -0.006991210094449025]
  # accelerometer_bias: [0.202951, -0.289404, -0.0117763]

  # 2023-02-18-10-06-58 (Corridor lab to gate)
  # gyroscope_bias: [-0.0077754570758159945,  0.022726878314022703, -0.004991210094449025]
  # accelerometer_bias: [0.178425, -0.256016, -0.00687119]
  # gyroscope_bias: [-0.0077754570758159945,  0.022726878314022703, -0.004991210094449025]
  # accelerometer_bias: [0.178425, 0, -0.00687119]
  # gyroscope_bias: [-0.0077754570758159945,  0.022726878314022703, -0.004991210094449025]
  # accelerometer_bias: [0.178425, 0, -0.00687119]

  # 2023-02-14-16-53-30 (lab to corridor)
  # gyroscope_bias: [-0.0071523435532401805, 0.02258783800128311, -0.003771635028351893]
  # accelerometer_bias: [0.243418, -0.190075, -0.000739752]

  # 2023-02-18-14-59-00 (Undergrad lab 2)
  # gyroscope_bias: [-0.0064385012123877525, 0.022180384628990465, -0.002385940742859208]
  # accelerometer_bias: [0.170454, -0.206629, -0.0148421]


  # gyroscope_bias: [-0.00927764, 0.0230112, -0.0125141]
  gyroscope_bias: [0, 0, -0.002]
  accelerometer_bias: [0.24771, -0.301667, -0.0150318]


# IMU noise parameters:
noises:
  gyroscope_std: 0.1  # 0.000061087, 0.1, 0.04
  accelerometer_std: 0.1 # 0.0013734, 0.1, 0.65
  gyroscope_bias_std: 0.1 # 0.1, 0.04
  accelerometer_bias_std: 0.1 # 0.1, 0.65