subscribers:
  # Name all the topics to subscribe from in this section. You may also redefine the variable name
  # as long as you can load the yaml variable in your main file
  imu_topic: "/girona500/navigator/imu"
  velocity_topic: "/girona500/navigator/dvl_velocity"

publishers:
  # Define publish rate and topics for publishers
  pose_publish_rate: 1000 # Hz
  pose_publish_topic: "/girona500/vanila_inekf/pose"
  pose_frame: "/odom"

  path_publish_rate: 100 # Hz
  path_publish_topic: "/girona500/vanila_inekf/path"
