// Generated by gencpp from file custom_sensor_msgs/TensegrityKin.msg
// DO NOT EDIT!


#ifndef CUSTOM_SENSOR_MSGS_MESSAGE_TENSEGRITYKIN_H
#define CUSTOM_SENSOR_MSGS_MESSAGE_TENSEGRITYKIN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_sensor_msgs
{
template <class ContainerAllocator>
struct TensegrityKin_
{
  typedef TensegrityKin_<ContainerAllocator> Type;

  TensegrityKin_()
    : header()
    , contact()
    , kinematics()  {
    }
  TensegrityKin_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , contact(_alloc)
    , kinematics(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _contact_type;
  _contact_type contact;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _kinematics_type;
  _kinematics_type kinematics;





  typedef boost::shared_ptr< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> const> ConstPtr;

}; // struct TensegrityKin_

typedef ::custom_sensor_msgs::TensegrityKin_<std::allocator<void> > TensegrityKin;

typedef boost::shared_ptr< ::custom_sensor_msgs::TensegrityKin > TensegrityKinPtr;
typedef boost::shared_ptr< ::custom_sensor_msgs::TensegrityKin const> TensegrityKinConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator1> & lhs, const ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.contact == rhs.contact &&
    lhs.kinematics == rhs.kinematics;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator1> & lhs, const ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_sensor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> >
{
  static const char* value()
  {
    return "275ada28e580d76636865f8b13e2b576";
  }

  static const char* value(const ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x275ada28e580d766ULL;
  static const uint64_t static_value2 = 0x36865f8b13e2b576ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_sensor_msgs/TensegrityKin";
  }

  static const char* value(const ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool[] contact\n"
"float32[] kinematics\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.contact);
      stream.next(m.kinematics);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TensegrityKin_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_sensor_msgs::TensegrityKin_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "contact[]" << std::endl;
    for (size_t i = 0; i < v.contact.size(); ++i)
    {
      s << indent << "  contact[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.contact[i]);
    }
    s << indent << "kinematics[]" << std::endl;
    for (size_t i = 0; i < v.kinematics.size(); ++i)
    {
      s << indent << "  kinematics[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kinematics[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_SENSOR_MSGS_MESSAGE_TENSEGRITYKIN_H
