
settings:
  ########################
  # Orientation Settings #
  ########################
  # We assume the body frame to be at the imu position.
  # X pointing forward, Y to the left, Z pointing up.
  rotation_imu2body: [0, 0.7071, -0.7071, 0] # Orientation from IMU to the body frame. [w, x, y, z]

  ### Setting for filter dimension ###
  # if flat_ground is true, the angular velocity filter would enforce the roll and pitch velocity to be zero
  # if flat_ground is false, the filter would only update the yaw velocity
  flat_ground: false

noises:
  ang_vel_std: 0.1
  ang_vel_bias_std: 0.1
  filter_std: 0.05
  filter_bias_std: 0.05
  imu_meas_noise_std: 0.01
  encoder_meas_noise_std: 0.01

priors:
  ang_vel_bias:  [0.00124314,-0.00037725,-0.00254523]