noises:
  ang_vel_std: 0.1
  ang_vel_bias_std: 0.1
  filter_std: 0.05
  filter_bias_std: 0.05
  imu_meas_noise_std: 0.01
  encoder_meas_noise_std: 0.01

priors:
  ang_vel_bias:  [0.00124314,-0.00037725,-0.00254523]